version: "2"

services:
  ember:
    build: .
    volumes:
      - ./ember:/usr/src/app
      - /usr/src/app/bower_components
      - /usr/src/app/node_modules
    environment:
      TZ: America/Chicago
    env_file:
      - env.ini
